# This qBittorrent does not use VPN.
# Use this file only when Gluetun is not setup.

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
      - WEBUI_PORT=${WEBUI_PORT}
      - TORRENTING_PORT=${LISTEN_PORT}
    volumes:
      - /home/ypei/libraries/docker/qbittorrent/config:/config
      - /mnt/pve-white/shared/downloads/qbittorrent:/downloads
    # network_mode: "container:gluetun"  # in case use Gluetun, comment ports
    ports:
      - ${WEBUI_PORT}:${WEBUI_PORT}
      - ${LISTEN_PORT}:${LISTEN_PORT}
      - ${LISTEN_PORT}:${LISTEN_PORT}/udp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
