services:
  xiaoya:
    image: xiaoyaliu/alist:latest
    container_name: xiaoya_alist
    restart: unless-stopped
    env_file: .env
    ports:
      - ${WEBUI_PORT}:80
    volumes:
      - /home/ypei/libraries/docker/xiaoya/tokens:/data

  xiaoya_helper:
    image: geekotaku/xiaoyahelper:latest
    container_name: xiaoya_helper
    restart: unless-stopped
    environment:
      - cron=0 2 * * *
    volumes:
      - /home/ypei/libraries/docker/xiaoya/tokens:/data
