services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    env_file: .env
    group_add:
      - 107  # Group ID of UHD630 by running stat -c '%g' /dev/dri/renderD128
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    init: true
    volumes:
      # Do not change this line as otherwise the built-in backup solution will not work
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge # add to the same network as docker run would do
    ports:
      - ${AIO_PORT}:8080
    environment:
      APACHE_PORT: ${APACHE_PORT}
      # APACHE_IP_BINDING: 0.0.0.0  # Comment after initial installation
      NEXTCLOUD_DATADIR: /home/ypei/libraries/docker/nextcloud/data
      NEXTCLOUD_MEMORY_LIMIT: 1024M
      NEXTCLOUD_ENABLE_DRI_DEVICE: true
      SKIP_DOMAIN_VALIDATION: true
      TALK_PORT: ${TALK_PORT}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  nextcloud_aio_mastercontainer:
    # Do not change this line as otherwise the built-in backup solution will not work
    name: nextcloud_aio_mastercontainer
