services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=022
      - TZ=America/Los_Angeles
    ports:
      - ${PORT}:5244
    volumes:
      - /home/ypei/libraries/docker/alist/data:/opt/alist/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
