---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Hypervisor:
    - pve-router:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: Router
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
            node: pve-router
    - pve-white:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: Prod
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
            node: pve-white
    - pve-black:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: Dev
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
            node: pve-black

- Docker:
    - Portainer:
        icon: portainer.svg
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: Docker Management
        widget:
            type: portainer
            url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
            env: "{{HOMEPAGE_VAR_PORTAINER_ENV}}"
            key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
    - WatchTower:
        icon: watchtower.svg
        href: "{{HOMEPAGE_VAR_WATCHTOWER_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_WATCHTOWER_URL}}"
        description: Docker Image Updater
        widget:
          type: watchtower
          url: "{{HOMEPAGE_VAR_WATCHTOWER_METRIC}}"
          key: "{{HOMEPAGE_VAR_WATCHTOWER_KEY}}"

- Storage:
    - DSM-7:
        icon: synology-dsm.svg
        href: "{{HOMEPAGE_VAR_DSM_PROD_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_DSM_PROD_URL}}"
        description: pve-white
        widget:
            type: diskstation
            url: "{{HOMEPAGE_VAR_DSM_PROD_URL}}"
            username: remote-stats
            password: "{{HOMEPAGE_VAR_DSM_PROD_STATS_PASSWORD}}"
            volume: volume_1
    - DSM-7 Dev:
        icon: synology-dsm.svg
        href: "{{HOMEPAGE_VAR_DSM_DEV_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_DSM_DEV_URL}}"
        description: pve-black
        widget:
            type: diskstation
            url: "{{HOMEPAGE_VAR_DSM_DEV_URL}}"
            username: remote-stats
            password: "{{HOMEPAGE_VAR_DSM_DEV_STATS_PASSWORD}}"
            volume: volume_1
    - TrueNAS Scale:
        icon: truenas.svg
        href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        description: pve-black
        widget:
            type: truenas
            url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
            username: "{{HOMEPAGE_VAR_TRUENAS_USERNAME}}"
            password: "{{HOMEPAGE_VAR_TRUENAS_PASSWORD}}"
            enablePools: true
    - Nextcloud:
        icon: nextcloud.svg
        href: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
        description: File Sharing & Transfer
        widget:
            type: nextcloud
            url: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
            username: "{{HOMEPAGE_VAR_NEXTCLOUD_USERNAME}}"
            password: "{{HOMEPAGE_VAR_NEXTCLOUD_PASSWORD}}"

- Media:
    - Immich:
        icon: immich.svg
        href: "{{HOMEPAGE_VAR_IMMICH_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_IMMICH_URL}}"
        description: Photo Management
        widget:
            type: immich
            url: "{{HOMEPAGE_VAR_IMMICH_URL}}"
            key: "{{HOMEPAGE_VAR_IMMICH_KEY}}"
            version: 2 # optional, default is 1
    - Jellyfin:
        icon: jellyfin.svg
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: Media System
        widget:
            type: jellyfin
            url: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
            key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
    - Navidrome:
        icon: navidrome.svg
        href: "{{HOMEPAGE_VAR_NAVIDROME_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_NAVIDROME_URL}}"
        description: Music Management
        widget:
            type: navidrome
            url: "{{HOMEPAGE_VAR_NAVIDROME_URL}}"
            user: "{{HOMEPAGE_VAR_NAVIDROME_USER}}"
            token: "{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}"
            salt: "{{HOMEPAGE_VAR_NAVIDROME_SALT}}"

- Networking:
    - iStoreOS:
        icon: openwrt.svg
        href: "{{HOMEPAGE_VAR_OPENWRT_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_OPENWRT_URL}}"
        description: iStoreOS
        widget:
            type: openwrt
            url: "{{HOMEPAGE_VAR_OPENWRT_URL}}"
            username: "{{HOMEPAGE_VAR_OPENWRT_USERNAME}}"
            password: "{{HOMEPAGE_VAR_OPENWRT_PASSWORD}}"
            interfaceName: eth1 # optional
    - NPM:
        icon: nginx-proxy-manager.svg
        href: "{{HOMEPAGE_VAR_NPM_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_NPM_URL}}"
        description: Nginx Proxy Manager
        widget:
            type: npm
            url: "{{HOMEPAGE_VAR_NPM_URL}}"
            username: "{{HOMEPAGE_VAR_NPM_USERNAME}}"
            password: "{{HOMEPAGE_VAR_NPM_PASSWORD}}"
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        href: "{{HOMEPAGE_VAR_SPEEDTEST_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_SPEEDTEST_URL}}"
        description: Speedtest Tracker
        widget:
            type: speedtest
            url: "{{HOMEPAGE_VAR_SPEEDTEST_URL}}"
            bitratePrecision: 3 # optional, default is 0
    - ChangeDetection.io:
        icon: changedetection.svg
        siteMonitor: "{{HOMEPAGE_VAR_CHANGEDETECTION_URL}}"
        description: Website Change Detector
        widget:
          type: changedetectionio
          url: "{{HOMEPAGE_VAR_CHANGEDETECTION_URL}}"
          key: "{{HOMEPAGE_VAR_CHANGEDETECTION_API_KEY}}"
    - Gluetun:
        icon: gluetun.png
        siteMonitor: "{{HOMEPAGE_VAR_GLUETUN_URL}}"
        description: VPN Client for Containers
        widget:
          type: gluetun
          url: "{{HOMEPAGE_VAR_GLUETUN_URL}}"
          key: "{{HOMEPAGE_VAR_GLUETUN_API_KEY}}"
    - WireGuard-Ampere:
        icon: wireguard.svg
        href: "{{HOMEPAGE_VAR_WIREGUARD_AMPERE_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_WIREGUARD_AMPERE_URL}}"
        description: WireGuard VPN Server on OCI Ampere
        widget:
          type: wgeasy
          url: "{{HOMEPAGE_VAR_WIREGUARD_AMPERE_URL}}"
          password: "{{HOMEPAGE_VAR_WIREGUARD_AMPERE_PASSWORD}}"
          threshold: 2 # optional
    - WireGuard-AMD-0:
        icon: wireguard.svg
        href: "{{HOMEPAGE_VAR_WIREGUARD_AMD0_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_WIREGUARD_AMD0_URL}}"
        description: WireGuard VPN Server on OCI AMD-0
        widget:
          type: wgeasy
          url: "{{HOMEPAGE_VAR_WIREGUARD_AMD0_URL}}"
          password: "{{HOMEPAGE_VAR_WIREGUARD_AMD0_PASSWORD}}"
          threshold: 2 # optional
    - WireGuard-AMD-1:
        icon: wireguard.svg
        href: "{{HOMEPAGE_VAR_WIREGUARD_AMD1_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_WIREGUARD_AMD1_URL}}"
        description: WireGuard VPN Server on OCI AMD-1
        widget:
          type: wgeasy
          url: "{{HOMEPAGE_VAR_WIREGUARD_AMD1_URL}}"
          password: "{{HOMEPAGE_VAR_WIREGUARD_AMD1_PASSWORD}}"
          threshold: 2 # optional
    
- Download:
    - qBittorrent:
        icon: qbittorrent.svg
        href: "{{HOMEPAGE_VAR_QB_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_QB_URL}}"
        description: BitTorrent Client
        widget:
            type: qbittorrent
            url: "{{HOMEPAGE_VAR_QB_URL}}"
            username: "{{HOMEPAGE_VAR_QB_USERNAME}}"
            password: "{{HOMEPAGE_VAR_QB_PASSWORD}}"
    - BaiduYun:
        icon: /images/baiduyun.png
        href: "{{HOMEPAGE_VAR_BAIDUYUN_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_BAIDUYUN_URL}}"
        description: BaiduYun Client
    - AriaNg:
        icon: ariang.png
        href: "{{HOMEPAGE_VAR_ARIANG_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_ARIANG_URL}}"
        description: Aria2 Client

- Utility:
    - SearXNG:
        icon: searxng.png
        href: "{{HOMEPAGE_VAR_SEARXNG_URL}}"
        description: Privacy-focused Aggregated Browser
    - Vaultwarden:
        icon: vaultwarden.svg
        href: "{{HOMEPAGE_VAR_VAULTWARDEN_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_VAULTWARDEN_URL}}"
        description: Password Manager
    - Openlist:
        icon: openlist.svg
        href: "{{HOMEPAGE_VAR_OPENLIST_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_OPENLIST_URL}}"
        description: Cloud Storages in One Place
    - Xiaoya:
        icon: si-alibabacloud-#FF6A00
        href: "{{HOMEPAGE_VAR_XIAOYA_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_XIAOYA_URL}}"
        description: Xiaoya Alist
    - Music Tag Web:
        icon: /images/music-tag-web.png
        href: "{{HOMEPAGE_VAR_MUSIC_TAG_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_MUSIC_TAG_URL}}"
        description: Online Music Tag Editor/Scraper
    - Omni-tools:
        icon: sh-omnitools.svg
        siteMonitor: "{{HOMEPAGE_VAR_OMNITOOLS_URL}}"
        href: "{{HOMEPAGE_VAR_OMNITOOLS_URL}}"
        description: Handy tools for occasionally use
    - FastAPI-DLS:
        icon: si-nvidia-#76B900
        siteMonitor: "{{HOMEPAGE_VAR_FASTAPI_DLS_URL}}"
        description: Delegated License Service for Nvidia vGPU
    - KMS Server:
        icon: microsoft-to-do.svg
        description: Local Microsoft KMS Server
    - ArchiveBox:
        icon: archivebox.png
        siteMonitor: "{{HOMEPAGE_VAR_ARCHIVEBOX_URL}}"
        href: "{{HOMEPAGE_VAR_ARCHIVEBOX_URL}}"
        description: ArchiveBox
    - Qiandao:
        icon: /images/qiandao.png
        href: "{{HOMEPAGE_VAR_QIANDAO_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_QIANDAO_URL}}"
        description: Qiaodao Automation
    - UnblockNetEaseMusic:
        icon: si-neteasecloudmusic-#D43C33
        description: Unblock NetEase Music Service
