services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: unless-stopped
    env_file: .env
    ports:
      - ${HTTPS_PORT}:443     # local DNS usage
      - ${HTTP_PORT}:80    # hide HTTP for now
      - ${WEBUI_PORT}:81    # management port
    volumes:
      - /home/ypei/libraries/docker/npm/data:/data
      - /home/ypei/libraries/docker/npm/letsencrypt:/etc/letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
